PROTOTYNE/PROTOTYNE_BE

- src/main/java/com/prototyne/domain/ADD_set.java
- src/main/java/com/prototyne/domain/Alarm.java
- src/main/java/com/prototyne/domain/Event.java
- src/main/java/com/prototyne/domain/Feedback.java
- src/main/java/com/prototyne/domain/FeedbackImage.java
- src/main/java/com/prototyne/domain/Investment.java
- src/main/java/com/prototyne/domain/Product.java
- src/main/java/com/prototyne/domain/Ticket.java
- src/main/java/com/prototyne/domain/User.java
related #7
default값 추가
NOT NULL인 필드에 모두 @Column(nullable = false) 코드 추가
> fix: 엔티티 default값 추가

- build.gradle
- src/main/java/com/prototyne/apiPayload/config/AmazonConfig.java
- src/main/java/com/prototyne/aws/s3/AmazonS3Manager.java
- src/main/java/com/prototyne/converter/TempConverter.java
- src/main/java/com/prototyne/service/TempService/TempCommandService.java
- src/main/java/com/prototyne/service/TempService/TempCommandServiceImpl.java
- src/main/java/com/prototyne/web/controller/TempRestController.java
- src/main/java/com/prototyne/web/dto/TempRequest.java
- src/main/java/com/prototyne/web/dto/TempResponse.java
- src/main/resources/application.yml
#4 S3 설정 및 이미지 업로드
S3 연결 후 이미지 업로드 테스트
- 동일 이름의 이미지 방지를 위해 uuid 엔티티 구현 필요해보임 -> 언제?
- s3 연결을 위한 액세스키 .env 파일에 따로 저장
- 단일 이미지만 테스트 -> 여러장은?
> feat: s3 이미지 업로드 테스트 완료

- .github/workflows/CICD.yml
- src/main/java/com/prototyne/converter/UserConverter.java
- src/main/java/com/prototyne/domain/User.java
- src/main/java/com/prototyne/service/DeliveryService/DeliveryService.java
- src/main/java/com/prototyne/service/DeliveryService/DeliveryServiceImpl.java
- src/main/java/com/prototyne/service/LoginService/KakaoServiceImpl.java
- src/main/java/com/prototyne/web/controller/DeliveryController.java
- src/main/java/com/prototyne/web/controller/LoginController.java
- src/main/java/com/prototyne/web/dto/DeliveryDto.java
closed #22 
feat: 배송지 관련 필드 추가
feat: 배송지 DTO, Controller 제작
feat: 배송지 조회 api 완료
feat: 배송지 수정 api 완료
> [Feat] 배송지 조회 수정 api 작성

- .github/workflows/CICD.yml
- src/main/java/com/prototyne/service/LoginService/KakaoServiceImpl.java
- src/main/java/com/prototyne/web/dto/UserDto.java
close #36 
PR배포 해제
login dto : newUser -> signupComplete
긴급 사항이라 바로 merge 하겠습니다!
> [bug] pr배포 해제 login dto 수정

- src/main/java/com/prototyne/domain/Product.java
- src/main/java/com/prototyne/web/dto/ProductDTO.java
> Docs: Product 엔티티 썸네일 추가

- src/main/java/com/prototyne/converter/MyProductConverter.java
- src/main/java/com/prototyne/repository/FeedbackRepository.java
- src/main/java/com/prototyne/repository/MyProductRepository.java
- src/main/java/com/prototyne/service/MyProductService/MyProductService.java
- src/main/java/com/prototyne/service/MyProductService/MyProductServiceImpl.java
- src/main/java/com/prototyne/web/controller/MyProductController.java
- src/main/java/com/prototyne/web/dto/MyProductDto.java
#42 
feat: 체험 전체보기 내역 API 구현
feat: 체험 신청중인 내역 API 구현
feat: 체험 당첨 내역 API 구현
feat: 체험 작성완료 내역 API 구현
feat: 체험 종료 내역 API 구현
헷갈리실 수 있을 것 같아 체험 분류 정리한 내용 첨부합니다.
>신청 (`전체보기` = 당첨 발표 전 or 미당첨 or 나머지 )
> - 당첨 발표 전 = `신청>신청중인 체험` (*발표일 D-nn)
> - 당첨 발표 후
>    - 당첨된 것
>        - 후기 작성 전 = `당첨` (*배송 상태)
>        - 후기 작성 후
>            - 최종 발표일 전 = `작성 완료` (*발표일)
>            - 최종 발표일 후 = `종료` (*완료/패널티)
>    - 당첨되지 않은 것 = `신청>전체보기` (미당첨)
데이터 적재: 모든 경우의 수가 포함되도록 investment / event / feedback 테이블에 데이터 추가한 후 테스트하였습니다.
- apply가 false인 investment id 9번 제외, true인 나머지만 반환되는 것 확인
- `calculatedStatus`에서 디데이값(investment id: 2) / 미당첨(investment id: 3) / (그 외) 당첨 모든 케이스 알맞게 값 들어있음 확인
<br/><br>
- status가 `신청`이면서 releaseStart이 현재시점보다 나중인 케이스만 반환 
- 남은 디데이 계산 값 `ddayToOngoing` 에 들어있음 확인
<br/><br/>
- status가 `당첨`인 …
> [Feat] 체험내역관련 API 구현

- src/main/java/com/prototyne/converter/MyProductConverter.java
- src/main/java/com/prototyne/converter/ProductConverter.java
- src/main/java/com/prototyne/domain/User.java
- src/main/java/com/prototyne/repository/FeedbackRepository.java
- src/main/java/com/prototyne/repository/HeartRepository.java
- src/main/java/com/prototyne/repository/MyProductRepository.java
- src/main/java/com/prototyne/service/MyProductService/MyProductService.java
- src/main/java/com/prototyne/service/MyProductService/MyProductServiceImpl.java
- src/main/java/com/prototyne/service/ProductService/EventService.java
- src/main/java/com/prototyne/service/ProductService/EventServiceImpl.java
- src/main/java/com/prototyne/web/controller/MyProductController.java
- src/main/java/com/prototyne/web/controller/ProductController.java
- src/main/java/com/prototyne/web/dto/MyProductDto.java
- src/main/java/com/prototyne/web/dto/ProductDTO.java
> [중요] Merge develop to Main v3

- .github/workflows/CICD.yml
- src/main/java/com/prototyne/domain/Product.java
- src/main/java/com/prototyne/service/TicketService/TicketService.java
- src/main/java/com/prototyne/service/TicketService/TicketServiceImpl.java
- src/main/java/com/prototyne/web/controller/DeliveryController.java
- src/main/java/com/prototyne/web/controller/TicketController.java
- src/main/resources/application.yml
> [Feat] 티켓 구매 api

- src/main/java/com/prototyne/converter/ProductConverter.java
- src/main/java/com/prototyne/repository/HeartRepository.java
- src/main/java/com/prototyne/service/ProductService/EventService.java
- src/main/java/com/prototyne/service/ProductService/EventServiceImpl.java
- src/main/java/com/prototyne/web/controller/ProductController.java
- src/main/java/com/prototyne/web/dto/ProductDTO.java
#45 
1. 홈 화면 api 추가 및 검색 조회, 카테고리 선택 조회 api에 북마크 여부 추가
2. 충돌 해결 1 (시제품 상세에 북마크 여부 머지)
3. 충돌 해결 2 (시제품 관련 검색어 api들(추가, 조회, 삭제, 다 삭제) 머지)
1.
2.
3.
> [Feat] 홈 화면 api 추가

- src/main/java/com/prototyne/web/controller/ProductController.java
- src/main/java/com/prototyne/web/controller/SearchController.java
- src/main/resources/application.yml
#60 
최근 검색어 관련 API Endpoint 집합
기존: `/product/search` ▶ 변경 사항 적용: `/search` 
- swagger 태그 생성
- SearchController 생성 후 처리 
- application.yml 에 '08 . 시제품 - 최근 검색어' swagger 태그 추가 
- swagger 실행 화면
> [Fix] 검색어 API 관련

- src/main/java/com/prototyne/converter/UserConverter.java
- src/main/java/com/prototyne/web/dto/UserDto.java
#62 
- 프론트엔드 피드백 1번 사항 반영
- 유저 정보 조회(`GET /my/detail`) 시, username도 함께 반환되도록 수정
> [Fix] 유저정보 조회 시, username 추가하여 반환

- src/main/java/com/prototyne/converter/UserConverter.java
- src/main/java/com/prototyne/domain/User.java
- src/main/java/com/prototyne/web/dto/DeliveryDto.java
closed #55 
배송지 주소 -> 기본 주소 + 상세 주소로 분할
> [bug] 배송지 주소 분할

- src/main/java/com/prototyne/converter/MyProductConverter.java
- src/main/java/com/prototyne/web/controller/MyProductController.java
- src/main/java/com/prototyne/web/dto/MyProductDto.java
#66 
/reviewed -> /selected
기능의 의미는 통하고 있어 명칭만 변경하고 그 외 큰 변경사항은 없습니다.
> [Fix] 체험내역 단계 수정

- src/main/java/com/prototyne/apiPayload/code/status/ErrorStatus.java
- src/main/java/com/prototyne/domain/Alarm.java
- src/main/java/com/prototyne/repository/AlarmRespository.java
- src/main/java/com/prototyne/service/AlarmService/AlarmService.java
- src/main/java/com/prototyne/service/AlarmService/AlarmServiceImpl.java
- src/main/java/com/prototyne/service/ApplicationService/ApplicationServiceImpl.java
- src/main/java/com/prototyne/web/controller/AlarmController.java
- src/main/java/com/prototyne/web/dto/AlarmDto.java
- src/main/java/com/prototyne/web/dto/InvestmentDTO.java
- src/main/resources/application.yml
> [feat] 알람 내역 열람 API 추가

- src/main/java/com/prototyne/apiPayload/config/WebConfig.java
closed #72 
PATCH 메소드 추가, 허용 도메인 설정
> [bug] PATCH 메소드 추가, 허용 도메인 설정

- src/main/java/com/prototyne/domain/User.java
- src/main/java/com/prototyne/service/LoginService/KakaoServiceImpl.java
> [fix] 로그인 문제 해결/ 엔티티 일부 수정

- src/main/java/com/prototyne/converter/UserConverter.java
> fix: 빌드 오류 수정

- src/main/java/com/prototyne/web/controller/HeartController.java
- src/main/java/com/prototyne/web/controller/MyProductController.java
> [Feat] 좋아요, 체험내역 에러코드 추가

- src/main/java/com/prototyne/apiPayload/code/status/ErrorStatus.java
- src/main/java/com/prototyne/service/SignupService/UserSignupServiceImpl.java
> [Bug] 회원가입 에러코드 추가

- src/main/java/com/prototyne/converter/ProductConverter.java
- src/main/java/com/prototyne/web/dto/ProductDTO.java
- src/main/resources/application.yml
#83 
- EventDetailsResponse에 productId 추가
- yml 수정 - path 삭제
> Fix: 시제품 상세 화면 api - productId 추가

- src/main/java/com/prototyne/service/TicketService/TicketServiceImpl.java
- src/main/java/com/prototyne/web/dto/TicketDto.java
#57 
티켓 개수 api에 기타 정보 추가
- usedTicket: 종료된 체험 기준으로 사용한 티켓
- appliedNum / selectedNum / ongoingNum / completedNum: 각 단계별 체험의 수
- 체험한 시제품 수 = completedNum
> [Feat] 티켓 개수 api에 기타 정보 추가

- src/main/resources/application.yml
> Fix: yml 수정 - path 추가

- src/main/java/com/prototyne/apiPayload/code/status/ErrorStatus.java
- src/main/java/com/prototyne/service/UserService/UserDetailServiceImpl.java
- src/main/java/com/prototyne/web/controller/MyController.java
- src/main/java/com/prototyne/web/dto/UserDto.java
closed #85 
- 추가 정보(addInfo) 관련 요청 시, 지정된 라벨 값만 전달하도록 수정
- 지정된 라벨은 이미지와 같다.
> fix: 유저 추가 정보 유효형식값만 전달하도록 수정

- src/main/java/com/prototyne/repository/HeartRepository.java
- src/main/java/com/prototyne/service/ApplicationService/ApplicationServiceImpl.java
- src/main/java/com/prototyne/service/ProductService/EventServiceImpl.java
#93 
- ApplicationServiceImpl - 문구 수정
- EventServiceImpl - findFirstByUserIdAndEvent로 변경
> Fix: 알람 api 문구 수정

- src/main/java/com/prototyne/converter/InvestmentConverter.java
#96 
체험신청 API - status값 : '신청'으로 저장
> Fix: 체험 신청 API-status 기본값-신청으로

- src/main/java/com/prototyne/converter/HeartConverter.java
- src/main/java/com/prototyne/web/dto/HeartDto.java
> [Feat] 좋아요 목록 dto에 이벤트 id 추가

- src/main/java/com/prototyne/domain/Alarm.java
- src/main/java/com/prototyne/service/ApplicationService/ApplicationServiceImpl.java
- src/main/java/com/prototyne/service/TicketService/TicketServiceImpl.java
closed #100 
티켓 구매/사용에 알림 내용 추가
> [feat] 티켓 구매/사용에 알림 추가

- src/main/java/com/prototyne/repository/InvestmentRepository.java
- src/main/java/com/prototyne/service/ApplicationService/ApplicationServiceImpl.java
- src/main/java/com/prototyne/service/FeedbackService/FeedbackServiceImpl.java
- src/main/java/com/prototyne/service/ProductService/EventServiceImpl.java
closed #102
상품 디테일 조회 에러 처리
이슈참고
> [bug] 상품 디테일 조회 에러 처리

- src/main/java/com/prototyne/domain/Enterprise.java
- src/main/java/com/prototyne/domain/enums/EnterpriseStatus.java
#107 
기업 엔티티 변경사항 반영
- 사업자등록번호에 의한 승인 여부 `status`는 enum(대기 or 승인)으로 추가
- category, size의 경우 추후 결정된 항목에 따라 enum으로 변경할 예정
> [Feat] 기업 엔티티 수정

- src/main/java/com/prototyne/StudyApplication.java
- src/main/java/com/prototyne/Users/service/PaymentService/KakaopayService.java
- src/main/java/com/prototyne/Users/service/PaymentService/KakaopayServiceImpl.java
- src/main/java/com/prototyne/Users/service/TicketService/TicketService.java
- src/main/java/com/prototyne/Users/service/TicketService/TicketServiceImpl.java
- src/main/java/com/prototyne/Users/web/controller/KakaopayController.java
- src/main/java/com/prototyne/Users/web/dto/KakaoPayDto.java
- src/main/java/com/prototyne/domain/enums/TicketOption.java
- src/main/resources/application-secret.yml
- src/main/resources/application.yml
**해당 요구사항에 따라 티켓 카카오페이 결제 시스템 api 구현** 
테스트 완료
> [Feat] 결제시스템 준비 구현

- src/main/resources/application.yml
> [Bug] eip관련 환경변수 재설정

- src/main/java/com/prototyne/Users/service/PaymentService/KakaopayServiceImpl.java
- src/main/java/com/prototyne/Users/web/controller/TicketController.java
- src/main/java/com/prototyne/apiPayload/code/status/ErrorStatus.java
#111 
- 기존의 테스트용 티켓 발급 `/ticket/buy` API 삭제 
- ▶  카카오페이 결제 성공(`/kakaopay/success`) 시, 자동으로 티켓 발급되도록 수정
- 이후 `/ticket/all` 로 티켓 발급 내역 조회 시, 성공적으로 조회
> [Feat] kakaoPay 결제 성공 시, 티켓 발급 로직 구현

- .github/workflows/CICD.yml
- src/main/java/com/prototyne/Enterprise/service/EnterpriseService/EnterpriseServiceImpl.java
- src/main/java/com/prototyne/apiPayload/code/status/ErrorStatus.java
#132 
기업 로그인 승인상태 '대기'일 시 에러코드 `ENTERPRISE_ERROR_STATUS`로 추가
> [Feat] 기업 로그인 대기 상태 에러코드 추가

- src/main/java/com/prototyne/Users/service/PaymentService/PaymentScheduler.java
- src/main/java/com/prototyne/repository/PaymentRepository.java
#111 
- 진행되지 않은 결제(결제성공/결제실패) 에 대한 데이터 Scheduler이용하여 자동 삭제
> [Feat] kakaopay 결제 timeout 추가

- src/main/java/com/prototyne/Enterprise/service/LoginService/LoginServiceImpl.java
#138 
기업 로그인 에러처리 비밀번호 확인 후 승인상태 확인으로 순서변경
: 대기중인 기업이 비밀번호 틀렸을 때
: 대기중인 기업이 비밀번호 맞았을 때
> [Bug] 기업 로그인 에러처리

- src/main/java/com/prototyne/Enterprise/service/ReviewService/EntReviewService.java
- src/main/java/com/prototyne/Enterprise/service/ReviewService/EntReviewServiceImpl.java
- src/main/java/com/prototyne/Enterprise/web/controller/EntReviewController.java
- src/main/java/com/prototyne/Users/service/FeedbackService/FeedbackService.java
- src/main/java/com/prototyne/Users/service/FeedbackService/FeedbackServiceImpl.java
- src/main/java/com/prototyne/Users/web/controller/ReviewController.java
- src/main/java/com/prototyne/repository/InvestmentRepository.java
#125 
개별 설문조사 조회 API, 패널티 부여 API, User-후기 작성 텍스트 API, User-후기 작성 이미지 API에서
엔드포인트 (investmentId -> eventId) 변경
User-후기 작성 텍스트 API, User-후기 작성 이미지 API
Enterprise-개별 설문조사 조회 API, 패널티 부여 API
> [Bug] InvestmentId-> eventId로 변경

- src/main/java/com/prototyne/Enterprise/converter/EntReviewConverter.java
- src/main/java/com/prototyne/Enterprise/service/ReviewService/EntReviewService.java
- src/main/java/com/prototyne/Enterprise/service/ReviewService/EntReviewServiceImpl.java
- src/main/java/com/prototyne/Enterprise/web/controller/EntReviewController.java
- src/main/java/com/prototyne/Enterprise/web/dto/EntAllReviewResponseDTO.java
- src/main/java/com/prototyne/Enterprise/web/dto/EntReviewDTO.java
- src/main/java/com/prototyne/Users/service/FeedbackService/FeedbackService.java
- src/main/java/com/prototyne/Users/service/FeedbackService/FeedbackServiceImpl.java
- src/main/java/com/prototyne/Users/web/controller/ReviewController.java
- src/main/java/com/prototyne/repository/InvestmentRepository.java
- src/main/java/com/prototyne/repository/ProductRepository.java
> 125 feat 설문조사 조회 삭제 api 구현

- src/main/java/com/prototyne/Enterprise/converter/EntReviewConverter.java
- src/main/java/com/prototyne/Enterprise/converter/UserlistConverter.java
- src/main/java/com/prototyne/Enterprise/service/ReviewService/EntReviewService.java
- src/main/java/com/prototyne/Enterprise/service/ReviewService/EntReviewServiceImpl.java
- src/main/java/com/prototyne/Enterprise/web/controller/EntReviewController.java
- src/main/java/com/prototyne/Enterprise/web/dto/EntAllReviewResponseDTO.java
- src/main/java/com/prototyne/Enterprise/web/dto/EntReviewDTO.java
- src/main/java/com/prototyne/Enterprise/web/dto/UserlistDTO.java
- src/main/java/com/prototyne/repository/FeedbackRepository.java
- src/main/java/com/prototyne/repository/ProductRepository.java
#125 
전체 설문조사 조회 API -  response body 수정
> [Feat]: 전체 설문조사 조회 API 수정

- src/main/java/com/prototyne/Enterprise/web/controller/UserlistController.java
#150 
신청자 배송 정보 수정 API - 파라미터 명 한글->영어로 변경
> [Bug] 신청자 배송 정보 수정 API- 파라미터명 변경

- src/main/java/com/prototyne/Enterprise/web/controller/LoginController.java
- src/main/java/com/prototyne/Users/web/controller/OauthController.java
> fix: 로그아웃 API DELETE → POST로 변경

- src/main/java/com/prototyne/Enterprise/service/ReviewService/EntReviewServiceImpl.java
- src/main/java/com/prototyne/Users/converter/ReviewConverter.java
- src/main/java/com/prototyne/Users/service/FeedbackService/FeedbackServiceImpl.java
- src/main/java/com/prototyne/Users/service/ReviewService/ReviewService.java
- src/main/java/com/prototyne/Users/service/ReviewService/ReviewServiceImpl.java
- src/main/java/com/prototyne/Users/web/controller/ReviewController.java
- src/main/java/com/prototyne/Users/web/dto/ReviewDTO.java
* feat: speed(시속) 후기 작성 시 +10, 패널티 부여 시 -50점
* feat: 후기 질문 목록 조회 API-파라미터 변경, 시제품 정보 추가
* feat: speed(시속) 증감 폭 수정
> [Feat] speed(시속) 증감 추가 (#177)

- src/main/java/com/prototyne/config/WebConfig.java
> [bug] cors 정책 - 도메인 추가

- src/main/java/com/prototyne/config/WebConfig.java
> [docs] cors 정책 복구

- src/main/java/com/prototyne/Enterprise/converter/EventConverter.java
- src/main/java/com/prototyne/Enterprise/converter/ProductConverter.java
- src/main/java/com/prototyne/Enterprise/service/ProductService/ProductService.java
- src/main/java/com/prototyne/Enterprise/service/ProductService/ProductServiceImpl.java
- src/main/java/com/prototyne/Enterprise/service/ReviewService/EntReviewServiceImpl.java
- src/main/java/com/prototyne/Enterprise/web/controller/ProductController.java
- src/main/java/com/prototyne/Enterprise/web/dto/EventDTO.java
- src/main/java/com/prototyne/Users/converter/MyProductConverter.java
- src/main/java/com/prototyne/Users/converter/ProductConverter.java
- src/main/java/com/prototyne/Users/converter/ReviewConverter.java
- src/main/java/com/prototyne/Users/service/EventService/EventServiceImpl.java
- src/main/java/com/prototyne/Users/service/FeedbackService/FeedbackServiceImpl.java
- src/main/java/com/prototyne/Users/service/MyProductService/MyProductServiceImpl.java
- src/main/java/com/prototyne/Users/service/ReviewService/ReviewService.java
- src/main/java/com/prototyne/Users/service/ReviewService/ReviewServiceImpl.java
- src/main/java/com/prototyne/Users/service/TicketService/TicketServiceImpl.java
- src/main/java/com/prototyne/Users/web/controller/ReviewController.java
- src/main/java/com/prototyne/Users/web/dto/ProductDTO.java
- src/main/java/com/prototyne/Users/web/dto/ReviewDTO.java
- src/main/java/com/prototyne/Users/web/dto/UserDto.java
- src/main/java/com/prototyne/apiPayload/code/status/ErrorStatus.java
- src/main/java/com/prototyne/domain/Event.java
- src/main/java/com/prototyne/repository/ProductImageRepository.java
- src/main/java/com/prototyne/repository/UserRepository.java
- src/main/java/com/prototyne/repository/querydsl/EventRepositoryCustomImpl.java
**release test를 위한 핫픽스 배포**
* feat: speed(시속) 후기 작성 시 +10, 패널티 부여 시 -50점
* feat: 후기 질문 목록 조회 API-파라미터 변경, 시제품 정보 추가
* feat: speed(시속) 증감 폭 수정
> [Release] 릴리즈 v1.0.4
